/*
Enter your query here.
*/

SELECT NAME = CASE WHEN GRADES.GRADE>7 THEN STUDENTS.NAME 
ELSE NULL 
END ,GRADES.GRADE , STUDENTS.MARKS 
FROM STUDENTS, GRADES 
WHERE STUDENTS.MARKS >= GRADES.MIN_MARK AND STUDENTS.MARKS <= GRADES.MAX_MARK ORDER BY GRADE DESC, NAME, MARKS;
